### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [Dai-44/go-next#200]
MVPリリースお疲れ様でした。
挙動の確認を行いました。LGTMです。
より良いものにするための改善点をお伝えします。

---

■`※ 応答がない場合、お手数ですが画面を再読み込みしてお試しください。`
ページに訪れた際にほぼリロードしないと「行き先を探す」が押せないため、リロードをしないといけない原因を調査して、極力この現象が起きないようにしましょう。

■テストを書きましょう
テストを書いていないようなので少しずつ書いていきましょう。

■ブックマーク
瞬時に2度押すとエラー画面がでてしまいますので対策を行いましょう。

■404・500ページ
Railsデフォルトのものではなく、自前で用意しましょう。

■思いつきのアイディア
ドライブ履歴詳細から行って良かったと思える場所をXで共有できるようにすると拡散されて良いかもと思いました。（サービスを使用して良いスポットへ行けたというのがわかるようなイメージです）

---

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。

看板は以下を参考に1週間を単位とした列を作成して、そこに各issueを配置してください。
https://github.com/users/Tsuchiya2/projects/2

また書き出したissueをもとに修正完了までのスケジュール、本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by Dai-44** [comment]
ご多用のところレビューいただき、また、より良いサービスとなるためのご助言も下さりありがとうございます！

ご指摘いただいた点をissueに追加し、週単位での看板を作成する形で本リリースまでのスケジュールを作成いたしました。
https://github.com/users/Dai-44/projects/1/views/1

修正完了は2/7(水), 本リリースは2/18(日)を予定しております。

ご確認のほど、よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
回答ありがとうございます！
（↑のリンク、404が出てしまったので変更しておきましょう）
引き続き開発頑張ってください！
